<a href="https://colab.research.google.com/github/sahithi18/Fred-Data/blob/main/FindingRetailSales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

# Load the data from the spreadsheet
data = pd.read_excel('/content/FindingRetailSalesBEAIssues.xlsx')

In [4]:
# Strip whitespace from column names to avoid any issues
data.columns = data.columns.str.strip()

In [5]:
data.head()

,Series,Description,NIPA Group,Release,Subindex,Transformation,Level Specification
0,ADPS,ADP Nonfarm Private Payroll Employment: Small ...,Consumption,ADP,"Employment, Unemployment & Hours",DIFFL(%d)/100,LAXEP1A@ADP22
1,ADPM,ADP Nonfarm Private Payroll Employment: Medium...,Consumption,ADP,"Employment, Unemployment & Hours",DIFFL(%d)/100,LAXEP2A@ADP22
2,ADPL,ADP Nonfarm Private Payroll Employment: Large ...,Consumption,ADP,"Employment, Unemployment & Hours",DIFFL(%d)/100,LAXEP3A@ADP22
3,ADPNM,ADP Nonfarm Private Payroll Employment: Natura...,Consumption,ADP,"Employment, Unemployment & Hours",DIFFL(%d)/100,LAXEPRA@ADP22
4,ADPCONST,ADP Nonfarm Private Payroll Employment: Constr...,Consumption,ADP,"Employment, Unemployment & Hours",DIFFL(%d)/100,LAXEPCA@ADP22

In [6]:

# Filtering rows by Subindex for specific categories
filtered_df = data[
    data['Subindex'].isin(['Sales, Orders & Inventories', 'Personal Consumption & Housing'])
]

In [7]:
filtered_df.head()

,Series,Description,NIPA Group,Release,Subindex,Transformation,Level Specification
122,CBHM,PCE: Total,Consumption,Personal Income & Outlays,Personal Consumption & Housing,DIFFL(%d)/100,CBHM
123,CDBHM,PCE: Durable Goods,Consumption,Personal Income & Outlays,Personal Consumption & Housing,DIFFL(%d)/100,CDBHM
124,CDVHM,PCE: Motor Vehicles & Parts,Consumption,Personal Income & Outlays,Personal Consumption & Housing,DIFFL(%d)/100,CDVHM@USNA
125,CDFDHM,PCE: Furnishings and Durable Household Equipment,Consumption,Personal Income & Outlays,Personal Consumption & Housing,DIFFL(%d)/100,CDFDHM@USNA
126,CDRGHM,PCE: Recreational Goods and Vehicles,Consumption,Personal Income & Outlays,Personal Consumption & Housing,DIFFL(%d)/100,CDRGHM@USNA

In [8]:
#Appling highlighting based on "Level Specification" column
def apply_highlight(row):
    if 'J' in row['Level Specification']:
        return ['background-color: red'] * len(row)
    else:
        return ['background-color: orange'] * len(row)

In [9]:
# Apply the function to highlight
highlighted_df = filtered_df_no_index.style.apply(apply_highlight, axis=1)

In [11]:
highlighted_df

In [12]:
# Converting highlighted DataFrame to an Excel file
output_file_path = 'highlighted_series_corrected.xlsx'
highlighted_df.to_excel(output_file_path, engine='openpyxl', index=False)

print(f"Highlighted file saved to {output_file_path}")

Highlighted file saved to highlighted_series_corrected.xlsx